# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fire.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fire.proto',
  package='fire',
  syntax='proto3',
  serialized_options=b'\n\013fireserviceB\020fire2ServiceImplP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nfire.proto\x12\x04\x66ire\"\"\n\x12\x63ontactFireRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1d\n\x0c\x66ireResponse\x12\r\n\x05value\x18\x01 \x01(\t\"P\n\rfireEmergency\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06injury\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\t\"\"\n\x12\x66ireResponseStream\x12\x0c\n\x04text\x18\x01 \x01(\t2\x85\x01\n\x04\x66ire\x12;\n\x0b\x63ontactFire\x12\x18.fire.contactFireRequest\x1a\x12.fire.fireResponse\x12@\n\remergencyFire\x12\x13.fire.fireEmergency\x1a\x18.fire.fireResponseStream0\x01\x42!\n\x0b\x66ireserviceB\x10\x66ire2ServiceImplP\x01\x62\x06proto3'
)




_CONTACTFIREREQUEST = _descriptor.Descriptor(
  name='contactFireRequest',
  full_name='fire.contactFireRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='fire.contactFireRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=54,
)


_FIRERESPONSE = _descriptor.Descriptor(
  name='fireResponse',
  full_name='fire.fireResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='fire.fireResponse.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=85,
)


_FIREEMERGENCY = _descriptor.Descriptor(
  name='fireEmergency',
  full_name='fire.fireEmergency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='fire.fireEmergency.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='injury', full_name='fire.fireEmergency.injury', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='fire.fireEmergency.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priority', full_name='fire.fireEmergency.priority', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=167,
)


_FIRERESPONSESTREAM = _descriptor.Descriptor(
  name='fireResponseStream',
  full_name='fire.fireResponseStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='fire.fireResponseStream.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=203,
)

DESCRIPTOR.message_types_by_name['contactFireRequest'] = _CONTACTFIREREQUEST
DESCRIPTOR.message_types_by_name['fireResponse'] = _FIRERESPONSE
DESCRIPTOR.message_types_by_name['fireEmergency'] = _FIREEMERGENCY
DESCRIPTOR.message_types_by_name['fireResponseStream'] = _FIRERESPONSESTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

contactFireRequest = _reflection.GeneratedProtocolMessageType('contactFireRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONTACTFIREREQUEST,
  '__module__' : 'fire_pb2'
  # @@protoc_insertion_point(class_scope:fire.contactFireRequest)
  })
_sym_db.RegisterMessage(contactFireRequest)

fireResponse = _reflection.GeneratedProtocolMessageType('fireResponse', (_message.Message,), {
  'DESCRIPTOR' : _FIRERESPONSE,
  '__module__' : 'fire_pb2'
  # @@protoc_insertion_point(class_scope:fire.fireResponse)
  })
_sym_db.RegisterMessage(fireResponse)

fireEmergency = _reflection.GeneratedProtocolMessageType('fireEmergency', (_message.Message,), {
  'DESCRIPTOR' : _FIREEMERGENCY,
  '__module__' : 'fire_pb2'
  # @@protoc_insertion_point(class_scope:fire.fireEmergency)
  })
_sym_db.RegisterMessage(fireEmergency)

fireResponseStream = _reflection.GeneratedProtocolMessageType('fireResponseStream', (_message.Message,), {
  'DESCRIPTOR' : _FIRERESPONSESTREAM,
  '__module__' : 'fire_pb2'
  # @@protoc_insertion_point(class_scope:fire.fireResponseStream)
  })
_sym_db.RegisterMessage(fireResponseStream)


DESCRIPTOR._options = None

_FIRE = _descriptor.ServiceDescriptor(
  name='fire',
  full_name='fire.fire',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=206,
  serialized_end=339,
  methods=[
  _descriptor.MethodDescriptor(
    name='contactFire',
    full_name='fire.fire.contactFire',
    index=0,
    containing_service=None,
    input_type=_CONTACTFIREREQUEST,
    output_type=_FIRERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='emergencyFire',
    full_name='fire.fire.emergencyFire',
    index=1,
    containing_service=None,
    input_type=_FIREEMERGENCY,
    output_type=_FIRERESPONSESTREAM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIRE)

DESCRIPTOR.services_by_name['fire'] = _FIRE

# @@protoc_insertion_point(module_scope)
