// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: police.proto

package policeservice;

public interface contactPDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:police.contactPDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
