// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: police.proto

package policeservice;

public interface emergencyPDResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:police.emergencyPDResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string situation = 2;</code>
   */
  java.lang.String getSituation();
  /**
   * <code>string situation = 2;</code>
   */
  com.google.protobuf.ByteString
      getSituationBytes();

  /**
   * <code>string address = 3;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string priority = 4;</code>
   */
  java.lang.String getPriority();
  /**
   * <code>string priority = 4;</code>
   */
  com.google.protobuf.ByteString
      getPriorityBytes();
}
