// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: police.proto

package policeservice;

public interface PDResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:police.PDResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
