// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: police.proto

package policeservice;

public final class police2ServiceImpl {
  private police2ServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_police_contactPDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_police_contactPDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_police_PDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_police_PDResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_police_PDEmergency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_police_PDEmergency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_police_emergencyPDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_police_emergencyPDResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014police.proto\022\006police\" \n\020contactPDReque" +
      "st\022\014\n\004text\030\001 \001(\t\"\033\n\nPDResponse\022\r\n\005value\030" +
      "\001 \001(\t\"Q\n\013PDEmergency\022\014\n\004name\030\001 \001(\t\022\021\n\tsi" +
      "tuation\030\002 \001(\t\022\017\n\007address\030\003 \001(\t\022\020\n\010priori" +
      "ty\030\004 \001(\t\"Y\n\023emergencyPDResponse\022\014\n\004name\030" +
      "\001 \001(\t\022\021\n\tsituation\030\002 \001(\t\022\017\n\007address\030\003 \001(" +
      "\t\022\020\n\010priority\030\004 \001(\t2\210\001\n\006police\0229\n\tcontac" +
      "tPD\022\030.police.contactPDRequest\032\022.police.P" +
      "DResponse\022C\n\013emergencyPD\022\023.police.PDEmer" +
      "gency\032\033.police.emergencyPDResponse(\0010\001B%" +
      "\n\rpoliceserviceB\022police2ServiceImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_police_contactPDRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_police_contactPDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_police_contactPDRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_police_PDResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_police_PDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_police_PDResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_police_PDEmergency_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_police_PDEmergency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_police_PDEmergency_descriptor,
        new java.lang.String[] { "Name", "Situation", "Address", "Priority", });
    internal_static_police_emergencyPDResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_police_emergencyPDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_police_emergencyPDResponse_descriptor,
        new java.lang.String[] { "Name", "Situation", "Address", "Priority", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
