// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medical.proto

package medicalservice;

public interface contactMedicalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:medical.contactMedical)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
