// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: medical.proto

package medicalservice;

public interface medicalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:medical.medicalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
